name: Deploy Stage Lambda Functions

on:
  push:
    branches: [main]

jobs:
  # Job 1: ai-agent-deploy
  ai-agent-deploy:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: AI-Agent-Test-Stage
      source-path: src/ai-agent
      zip-filename: ai-agent.zip
    secrets: inherit 
    
  # Job 2: ai-agent-iq-deploy
  ai-agent-iq-deploy:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Ai-Agent-IQTest-Stage
      source-path: src/ai-agent-iq
      zip-filename: ai-agent-iq.zip
    secrets: inherit

  # Job 3: agent-shortlisting-deploy
  agent-shortlisting-deploy:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Ai-Agent-Shortlisting-Stage
      source-path: src/agent-shortlisting
      zip-filename: agent-shortlisting.zip
    secrets: inherit

  # Job 4: client-focused-export-deploy
  client-focused-export-deploy:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Client-Focused-Export-Stage
      source-path: src/client-focused-export
      zip-filename: client-focused-export.zip
    secrets: inherit
    
  # Job 5: embedding-function-deploy
  embedding-function-deploy:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Embedding-Function-Stage
      source-path: src/embedding-function
      zip-filename: embedding-function.zip
    secrets: inherit

  # Job 6: relational-database-function
  relational-database-function:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Relational-Database-Function-Stage
      source-path: src/relational-database-function
      zip-filename: relational-database-function.zip
    secrets: inherit

  # Job 7: rt-iq-ai-agent-function
  rt-iq-ai-agent-function:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: RTIQ-Ai-Agent-Stage 
      source-path: src/rt-iq-ai-agent
      zip-filename: rt-iq-ai-agent.zip
    secrets: inherit

  # Job 8: shortlisting-audio-function
  shortlisting-audio-function:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: Shortlisting-Audio-Function-Stage
      source-path: src/shortlisting-audio-function
      zip-filename: shortlisting-audio-function.zip
    secrets: inherit

  # Job 9: sql-querying-function
  sql-querying-function:
    uses: ./.github/workflows/deployment/deploy-lambda.yml@main
    with:
      function-name: SQl-Querying-Function-Stage
      source-path: src/sql-querying-function
      zip-filename: sql-querying-function.zip
    secrets: inherit